app:
  serviceAccount:
    enabled: true
  name: operator
  image:
    repository: "onecx/onecx-test-operator"
  envCustom:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-pm:read ]