app:
  serviceAccount:
    enabled: true
  name: operator
  image:
    repository: "onecx/onecx-test-operator"
  envCustom:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: ONECX_TEST_SCHEDULER_TIMER
      value: "24h"
    - name: ONECX_TEST_SCHEDULER_SERVICES__0__URL
      value: ""
    - name: ONECX_TEST_SCHEDULER_SERVICES__0__SERVICES
      value: ""
    - name: ONECX_TEST_SCHEDULER_SERVICES__1__URL
      value: ""
    - name: ONECX_TEST_SCHEDULER_SERVICES__1__SERVICES
      value: ""
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ocx-pm:read]
