apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: {{ .Release.Name }}-{{ .Values.app.name }}-role
rules:
 - verbs:
    - "get"
    - "list"
    - "watch"
   apiGroups:
    - ''
   resources:
    - "pods"
    - "pods/log"
    - "services"
 - verbs:
    - "get"
    - "create"
   apiGroups:
    - ''
   resources:
    - "pods/exec"